name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出你的 fork 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 git 配置
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # 添加原仓库作为 upstream
      - name: Add upstream remote
        run: git remote add upstream https://github.com/home-assistant/supervisor.git

      # 获取原仓库的更改
      - name: Fetch upstream changes
        run: git fetch upstream

      # 合并原仓库的主分支更改到当前分支
      - name: Merge upstream changes
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories

      # 推送更改到你的 fork 仓库
      - name: Push changes
        run: git push origin main

